<center>
<img src="../../img/ods_stickers.jpg">
## Открытый курс по машинному обучению. Сессия № 3
Автор материала: программист-исследователь Mail.ru Group, старший преподаватель Факультета Компьютерных Наук ВШЭ Юрий Кашницкий. Материал распространяется на условиях лицензии [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). Можно использовать в любых целях (редактировать, поправлять и брать за основу), кроме коммерческих, но с обязательным упоминанием автора материала.

# <center> Домашнее задание № 1
## <center> Анализ данных по сердечно-сосудистым заболеваниям
*Идеальный просмотр Jupyter notebooks возможен только локально, GitHub и nbviewer могут неправильно отбражать формулы или картинки.*

**В задании предлагается с помощью Pandas ответить на несколько вопросов по данным о сердечно-сосудистых заболеваниях (качать данные не надо, они уже есть в репозитории). Данные использовались в соревновании [Ml Boot Camp 5](http://mlbootcamp.ru/round/12/sandbox/).**

**Заполните код в клетках (где написано "Ваш код здесь") и ответьте на вопросы.**

В соревновании предлагалось определить наличие/отсутствие сердечно-сосудистых заболеваний (ССЗ) по результатам осмотра пациента.

**Описание данных.**

Датасет сформирован из реальных клинических анализов, и в нём используются признаки, которые можно разбить на 3 группы:

Объективные признаки:

 - Возраст (age)
 - Рост (height)
 - Вес (weight)
 - Пол (gender)
 

Результаты измерения:

 - Артериальное давление верхнее и нижнее (ap_hi, ap_lo)
 - Холестерин (cholesterol)
 - Глюкоза (gluc)
 

Субъективные признаки (со слов пациентов):

 - Курение (smoke)
 - Употребление алкоголя (alco)
 - Физическая активность (active)
 
Целевой признак (который интересно будет прогнозировать):
 - Наличие сердечно-сосудистых заболеваний по результатам классического врачебного осмотра (cardio)

Значения показателей холестерина и глюкозы представлены одним из трех классов: норма, выше нормы, значительно выше нормы. Значения субъективных признаков — бинарны.

Все показатели даны на момент осмотра.

Мы будем работать только с обучающей выборкой и с помощью `Pandas` проведем первичный анализ данных. 

Из библиотек нам понадобятся только `NumPy` и `Pandas`.

import pandas as pd  
import numpy as np

Считываем данные из CSV-файла в объект pandas DataFrame.  

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/Admin/Jupyter project/data/train.csv", 
                 sep=';',
                 index_col='id')

Посмотрим на первые 5 записей.

In [3]:
df.head()

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
id                                                                          
0   18393       2     168    62.0    110     80            1     1      0   
1   20228       1     156    85.0    140     90            3     1      0   
2   18857       1     165    64.0    130     70            3     1      0   
3   17623       2     169    82.0    150    100            1     1      0   
4   17474       1     156    56.0    100     60            1     1      0   

    alco  active  cardio  
id                        
0      0       1       0  
1      0       1       1  
2      0       0       1  
3      0       1       1  
4      0       0       0

**<font color='red'>Вопрос 1.</font> Сколько мужчин и женщин представлено в этом наборе данных? Не было дано расшифровки признака "пол" (какому полу соответствует 1, а какому – 2 в признаке ``gender``) – это определите, посмотрев также на рост при разумном предположении, что в среднем мужчины выше (здесь и далее под средним понимается среднее арифметическое).**

**<font color='red'>Варианты:</font>**
- 45470 женщин и 24530 мужчин
- 45470 мужчин и 24530 женщин
- 45530 женщин и 24470 мужчин
- 45530 мужчин и 24470 женщин

In [4]:
# Show mean value of heigh and weight as sting

#Union in DataFrame by gender, Gender_Name,  Weight mean, Height mean, Count of gender and sort it on Height and Weight 
genderCount = pd.DataFrame(dict( Gender_Name = ['женщин', 'мужчин'],
                                    Height = df.groupby('gender')['height'].mean(), 
                                    Weight = df.groupby('gender')['weight'].mean(),
                                    Count = df.groupby('gender').size() )).sort_values(by = ['Height', 'Weight'])

#Make string with intresting to us value
countGenderType = str(genderCount['Count'][1]) + ' ' + str(genderCount['Gender_Name'][1]) + \
    ' и ' + str(genderCount['Count'][2])+ ' ' + str(genderCount['Gender_Name'][2])

#Save data for the next equations
womenSign = genderCount.index[0] # 1
manSign = genderCount.index[1] # 2


#Show string
countGenderType

'45530 женщин и 24470 мужчин'

We have 45530 women( женщин ) and 24470 man( мужчин )

**<font color='red'>Вопрос 2.</font> Кто в среднем реже указывает, что употребляет алкоголь – мужчины или женщины?**

**<font color='red'>Варианты:</font>**
- мужчины 
- женщины

In [5]:
#Show who less likely alcohol
                    # I have a question: sorts the index elements when we using groupby?    
lessLikelyAlco = pd.DataFrame(dict( Gender_Name = ['женщины', 'мужчины'],
                                    Alco = df.groupby('gender')['alco'].mean() )).sort_values(by = 'Alco')

#Show answer
lessLikelyAlco['Gender_Name'][1]

'женщины'

Who less likely alcohol? Women( женщины )

**<font color='red'>Вопрос 3.</font> Во сколько раз (округленно, `round`) процент курящих среди мужчин больше, чем процент курящих среди женщин (по крайней мере, по этим анкетным данным)?**

**<font color='red'>Варианты:</font>**
- 4
- 8
- 12
- 16

In [6]:
# Show, how many times men smoking more women

smokeCountMenWomen = pd.DataFrame(dict( SmokeWomen = df.query(f'gender == {womenSign}')['smoke'].value_counts(),
                                SmokeMen = df.query(f'gender == {manSign}')['smoke'].value_counts() ))

#Calculated percent and round it
# ( 100 * smokeMen / (smokeMen + noSmokeMen)) / (100 * smokeWomen / (smokeWomen + noSmokeWomen)) = % 
smokeCount = round((100* smokeCountMenWomen.SmokeMen[1] / (smokeCountMenWomen.SmokeMen[1] + smokeCountMenWomen.SmokeMen[0])) /
            (100* smokeCountMenWomen.SmokeWomen[1] / (smokeCountMenWomen.SmokeWomen[1] + smokeCountMenWomen.SmokeWomen[0])))

#Show answer
int(smokeCount)

12

How many times men smoking more women? On 12%

**<font color='red'>Вопрос 4.</font> Вы наверняка заметили, что значения возраста какие-то странные. Догадайтесь, в чём здесь измеряется возраст, и ответьте, на сколько месяцев (примерно) отличаются медианные значения возраста курящих и некурящих.**

**<font color='red'>Варианты:</font>**
- 10
- 15
- 20
- 25

In [7]:
#Show difference between life expectancy of smoking and don't smoking people in a months 
#difference between lifetime in a day
diffSmokeLifeTimeDay = df.groupby('smoke')['age'].median()

#Difference between lifetime in a months
diffSmokeLifeTimeMonth =round((diffSmokeLifeTimeDay[0] - diffSmokeLifeTimeDay[1])/365*12)

#Output
int(diffSmokeLifeTimeMonth) # ~15 month

20

Difference between lifetime in a months - 20

**<font color='red'>Вопрос 5.</font> В [статье](https://ru.wikipedia.org/wiki/Сердечно-сосудистый_риск) на Википедии про сердечно-сосудистый риск показана шкала SCORE для расчёта риска смерти от сердечно-сосудистого заболевания в ближайшие 10 лет. Вот она:**
<img src='https://habrastorage.org/webt/gg/38/vf/gg38vfl5ql8obqjmlsvt9es76p8.png' width=70%>

Давайте посмотрим на правый верхний прямоугольник, отображающий сегмент курящих мужчин в возрасте от 60 до 64 лет включительно. (Неочевидно, но тут для возраста и давления цифры означают верхнюю границу, и она не включается).

Видим 9-ку в левом нижнем углу этого прямоугольника и 47 – в правом верхнем. То есть если при этом систолическое (т.е. верхнее) артериальное давление – меньше 120 мм рт.ст., а уровень холестерина – 4 ммоль/л, то риск ССЗ оценивается примерно в 5 раз ниже, чем если бы давление лежало в интервале [160, 180), а холестерина было бы 8 ммоль/л.

Давайте посчитаем аналогичное значение, но на наших данных. 

Уточнения:
- Создайте новый признак ``age_years`` – возраст в годах, округлив до целых (`round`). Для данного примера отберите курящих мужчин от 60 до 64 лет включительно
- Категории уровня холестрина на рисунке и в наших данных отличаются. Отображение значений на картинке в значения признака ``cholesterol`` следующее: 4 ммоль/л $\rightarrow$ 1, 5-7 ммоль/л $\rightarrow$ 2, 8 ммоль/л $\rightarrow$ 3.
- Интересуют 2 подвыборки курящих мужчин возраста от 60 до 64 лет включительно: первая с верхним артериальным давлением строго меньше 120 мм рт.ст. и концентрацией холестерина – 4 ммоль/л, а вторая – с верхним артериальным давлением от 160 (включительно) до 180 мм рт.ст. (не включительно) и концентрацией холестерина – 8 ммоль/л.

Во сколько раз (округленно, `round`) отличаются доли больных людей (согласно целевому признаку, `cardio`) в этих двух подвыборках? Посчитайте на наших данных.

**<font color='red'>Варианты:</font>**
- 2
- 3
- 4
- 5

In [8]:
# Create new parameter
age_yearslim = [60,64]
df['age_years'] = round(df.age/365)
#Separate objects on age > 60 and age <= 64
ageLimit = df.query('age_years > @age_yearslim[0] and age_years <= @age_yearslim[1]').sort_values( by = 'age_years')

#Cholesterol level: 1 - 4mole/l, 2 - 5-7mole/l, 3 - 8mole/l
# We need two category: 
#        ap_hi < 120 and cholesterol == 1,  
#           160 <= ap_hi < 180 and cholecterol == 3
#Use hyperParameter {cardio} and found how many times the number of patients are differ in these categories

#Create two boolean equancy with hyperparameter - cardio, for two category
patientsFirstCat = ageLimit.query(f'smoke == 1 and gender == {manSign} and  \
                                  ap_hi < 120 and cholesterol == 1')['cardio'].value_counts()

patientsSecondCat = ageLimit.query(f'smoke == 1 and gender == {manSign} and ap_hi <= 160 and \
                                   ap_hi < 180 and cholesterol == 3')['cardio'].value_counts()

#Calculate the cardiac disease chance difference between the category
cardioDangDiff = round(( patientsSecondCat[1] / (patientsSecondCat[1]+patientsSecondCat[0]) ) /
                      ( patientsFirstCat[1] / (patientsFirstCat[1]+patientsFirstCat[0]) ))

#Output
int(cardioDangDiff)

3

Cardiac disease chance difference between the category - 3

**<font color='red'>Вопрос 6.</font> Постройте новый признак – BMI ([Body Mass Index](https://en.wikipedia.org/wiki/Body_mass_index)). Для этого надо вес в килограммах поделить на квадрат роста в метрах. Нормальными считаются значения BMI от 18.5 до 25. Выберите верные утверждения.**

**<font color='red'>Утверждения:</font>**
- Медианный BMI по выборке превышает норму
- У женщин в среднем BMI ниже, чем у мужчин
- У здоровых в среднем BMI выше, чем у больных
- В сегменте здоровых и непьющих мужчин в среднем BMI ближе к норме, чем в сегменте здоровых и непьющих женщин

In [9]:
#Create new parameter
df['BMI'] = df.weight/(np.square(df.height/100))

#Checking approvals:
AppFirstCheck = 'First - True' if df['BMI'].median() > 25 else 'First - False'
AppSecCheck = 'Second - True' if df.query(f'gender == {womenSign}')['BMI'].mean() < \
                                 df.query(f'gender == {manSign}')['BMI'].mean() else 'Second - False'

AppThirdCheck = 'Third - True' if df.query(f'cardio == 0')['BMI'].mean() > \
                                  df.query(f'cardio == 1')['BMI'].mean() else 'Third - False'

AppFourManMean = df.query(f' cardio == 0 and alco == 0 and gender == {manSign}')['BMI'].mean()
AppFourWomenMean = df.query(f'cardio == 0 and alco == 0 and gender == {womenSign}')['BMI'].mean()
AppFourthCheck = 'Fourth - True' if (abs(AppFourManMean - 25.0) < abs(AppFourWomenMean - 25.0)) and \
                                    (abs(AppFourManMean - 18.5) < abs(AppFourWomenMean - 18.5)) else 'Fourth - False'

#Create output form for answer 
for item in [AppFirstCheck, AppSecCheck, AppThirdCheck, AppFourthCheck]: print(item) 

First - True
Second - False
Third - False
Fourth - True


Approvals check results: <br>
First - True <br>
Second - False <br>
Third - False <br>
Fourth - True <br>

**<font color='red'>Вопрос 7.</font> ** Можно заметить, что данные не особо-то чистые, много в них всякой "грязи" и неточностей.

Отфильтруйте следующие сегменты пациентов (считаем это ошибками в данных)
- указанное нижнее значение артериального давления строго выше верхнего
- рост строго меньше 2.5%-перцентили или строго больше 97.5%-перцентили (используйте `pd.Series.quantile`, если не знаете, что это такое – прочитайте)
- вес строго меньше 2.5%-перцентили или строго больше 97.5%-перцентили

Это вовсе не вся чистка данных, которую можно было проделать, но пока остановимся на этом.

Сколько процентов данных (округленно, `round`) мы выбросили?

**<font color='red'>Варианты:</font>**
- 8
- 9
- 10
- 11

In [10]:
#Data filtration        
#save old data count
dataShapeOld = df.shape

# ap_lo > ap_hi, pd.Series.quantile(0.975) < height < pd.Series.quantile(0.025), 
#                pd.Series.quantile(0.025) < weight <  pd.Series.quantile(0.975)
df_best = df[(df.ap_hi < df.ap_lo ) 
        | (df.height < df.height.quantile(0.025)) 
        | (df.height > df.height.quantile(0.975))
        | (df.weight < df.weight.quantile(0.025)) 
        | (df.weight > df.weight.quantile(0.975))]
# Lost share data percent
lostShare = round(100 * df_best.shape[0]/dataShapeOld[0]) 
#Output
lostShare

10

We lost 10% of the all data